### ISSUE TITLE
float number rounding

### ISSUE THREAD

**Issue by hkristjan** [Media24si/UpnGenerator#1]
There is a bug in floating point number representation in the line where you assign the amount to QR code:
https://github.com/Media24si/UpnGenerator/blob/759603aa05fd30a0ee883f28b689d2d8d6317db4/src/UpnGenerator.php#L127

To reproduce the bug set the amount to 33.30. On UPN `znesek` will be 33,30 but on QR 33,29.

Here's an explanation why floating point numbers are tricky to deal with:
https://stackoverflow.com/questions/27107238/why-does-phps-sprintf-not-round-5s-reliably

I suggest you refactor it to this:
```sprintf('%011d', number_format($this->amount, 2, '', ''));```

**Comment by BostjanOb** [comment]
fixed in v3.0
