### ISSUE TITLE
Make due_date optional

### ISSUE THREAD

**Issue by jure123** [Media24si/UpnGenerator#3]
I suggest to make due_date optional. Now if we don't provide it, generate function throws error (since due_date->format() fails).

In your code you already try to handle this case in line 145: `$this->due_date->format('d.m.Y') ?? ''`, but I believe it's not working (format() function is called before `?? ''` even if due_date is null, so it throws error anyway). And you would also need to fix lines 80, 81.

I'm not sure if empty date is supported in QR codes though.

**Comment by BostjanOb** [comment]
Checked in documentation. Due date is not required. Added options ti be null.
